package cl.sgg.edm;
// Generated 11-feb-2016 0:18:43 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="USUARIOS"
    ,catalog="CLARITYCOW"
)
public class Usuarios  implements java.io.Serializable {


     private int userId;
     private String userName;
     private String password;
     private String firstName;
     private String lastName;
     private String userDesc;
     private boolean userValid;
     private String userMessage;
     private int userRol;

    public Usuarios() {
    }

    public Usuarios(int userId, String userName, String password, String firstName, String lastName, String userDesc, boolean userValid, String userMessage, int userRol) {
        this.userId = userId;
        this.userName = userName;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.userDesc = userDesc;
        this.userValid = userValid;
        this.userMessage = userMessage;
        this.userRol = userRol;
    }

	
    
   
     @Id 

    
    @Column(name="USERID", unique=true, nullable=false)
    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }
    
    @Column(name="USERNAME", unique=true, nullable=false)
    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }
    
    @Column(name="PASSWORD", unique=true, nullable=false)
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name="FIRSTNAME", unique=true, nullable=false)
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Column(name="LASTNAME", unique=true, nullable=false)
    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Column(name="USERDESC", unique=true, nullable=false)
    public String getUserDesc() {
        return userDesc;
    }

    public void setUserDesc(String userDesc) {
        this.userDesc = userDesc;
    }

    @Column(name="USERVALID", unique=true, nullable=false)
    public boolean isUserValid() {
        return userValid;
    }

    public void setUserValid(boolean userValid) {
        this.userValid = userValid;
    }

    @Column(name="USERMESSAGE", unique=true, nullable=false)
    public String getUserMessage() {
        return userMessage;
    }

    public void setUserMessage(String userMessage) {
        this.userMessage = userMessage;
    }

    @Column(name="USERROL", unique=true, nullable=false)
    public int getUserRol() {
        return userRol;
    }

    public void setUserRol(int userRol) {
        this.userRol = userRol;
    }

    @Override
    public String toString() {
        return "Usuarios{" + "userId=" + userId + ", userName=" + userName + ", password=" + password + ", firstName=" + firstName + ", lastName=" + lastName + ", userDesc=" + userDesc + ", userValid=" + userValid + ", userMessage=" + userMessage + ", userRol=" + userRol + '}';
    }
}


