package cl.sgg.edm;
// Generated 22-feb-2016 1:31:10 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="USUARIOS"
    ,catalog="CLARITYCOW"
)
public class Usuarios  implements java.io.Serializable {


     private Integer userid;
     private String username;
     private String password;
     private String firstname;
     private String lastname;
     private String userdesc;
     private boolean uservalid;
     private String usermessage;
     private int userrol;

    public Usuarios() {
    }

    public Usuarios(String username, String password, String firstname, String lastname, String userdesc, boolean uservalid, String usermessage, int userrol) {
       this.username = username;
       this.password = password;
       this.firstname = firstname;
       this.lastname = lastname;
       this.userdesc = userdesc;
       this.uservalid = uservalid;
       this.usermessage = usermessage;
       this.userrol = userrol;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="USERID", unique=true, nullable=false)
    public Integer getUserid() {
        return this.userid;
    }
    
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    
    @Column(name="USERNAME", nullable=false, length=50)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="PASSWORD", nullable=false, length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="FIRSTNAME", nullable=false, length=50)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    
    @Column(name="LASTNAME", nullable=false, length=50)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    
    @Column(name="USERDESC", nullable=false, length=50)
    public String getUserdesc() {
        return this.userdesc;
    }
    
    public void setUserdesc(String userdesc) {
        this.userdesc = userdesc;
    }

    
    @Column(name="USERVALID", nullable=false)
    public boolean isUservalid() {
        return this.uservalid;
    }
    
    public void setUservalid(boolean uservalid) {
        this.uservalid = uservalid;
    }

    
    @Column(name="USERMESSAGE", nullable=false, length=50)
    public String getUsermessage() {
        return this.usermessage;
    }
    
    public void setUsermessage(String usermessage) {
        this.usermessage = usermessage;
    }

    
    @Column(name="USERROL", nullable=false)
    public int getUserrol() {
        return this.userrol;
    }
    
    public void setUserrol(int userrol) {
        this.userrol = userrol;
    }




}


